name = "bv-website"
compatibility_date = "2025-04-01"
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "d1-biovault-website"
database_id = "35b334f1-0b99-43ad-bd1a-c5d497549618"
